name: Start Study

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Save start time
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq --arg now "$NOW" '.last_start = $now' study_log.json > tmp.json && mv tmp.json study_log.json

      - name: Commit update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add study_log.json
          git commit -m "Start study session"
          git push
